# Generated by Django 5.2.10 on 2026-02-19 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_userroleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default=django.utils.timezone.now, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserRoleAssignment',
        ),
    ]
