# Generated by Django 5.2.10 on 2026-04-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_branch_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram chat ID linked via the bot. Used for OTP delivery.', null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
    ]
