# Generated by Django 5.2.10 on 2026-08-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_branch_location_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='INN')),
                ('address', models.TextField(blank=True, verbose_name='Company Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Is Company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Is Customer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Date of Issue'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Passport Issued By'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_jshshr',
            field=models.CharField(blank=True, max_length=14, verbose_name='Passport JSHSHR (PINFL)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_scan',
            field=models.ImageField(blank=True, null=True, upload_to='passport_scans/', verbose_name='Passport Scan'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Passport Series'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
