# Generated by Django 5.2.10 on 2026-08-09 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_companyprofile_delete_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff_member',
            field=models.BooleanField(default=False, verbose_name='Is Staff Member'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('company', models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_staff_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
    ]
