# Generated by Django 5.2.10 on 2026-09-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_staff_member_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='director_name',
            field=models.CharField(blank=True, help_text='e.g. Arslanov Axror Jamolovich', max_length=255, verbose_name='Director Full Name'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='director_short_name',
            field=models.CharField(blank=True, help_text='e.g. A.J.Arslanov', max_length=100, verbose_name='Director Short Name'),
        ),
    ]
