# Generated by Django 5.2.10 on 2026-09-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_companyprofile_director_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('parts', models.IntegerField(default=1)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'is_company': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
