# Generated by Django 5.2.10 on 2026-09-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_role_staffprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account Number (x/r)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Name & Branch'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='jshshr',
            field=models.CharField(blank=True, max_length=14, verbose_name='PINFL (JSHSHR)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mfo',
            field=models.CharField(blank=True, max_length=10, verbose_name='MFO'),
        ),
    ]
