# Generated by Django 5.2.10 on 2026-10-02 06:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_companyprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secondary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Secondary phone number'),
        ),
    ]
