# Generated by Django 5.2.10 on 2026-08-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(verbose_name='Contract Date')),
                ('price_per_square', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price per m2')),
                ('down_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Down Payment')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Discount Amount')),
                ('payment_months', models.PositiveIntegerField(verbose_name='Payment Duration (Months)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Total Contract Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='building.apartment')),
                ('company', models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_contracts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Payment Amount')),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK', 'Bank Transfer'), ('MATERIAL', 'Material')], max_length=20, verbose_name='Payment Type')),
                ('transaction_id', models.CharField(blank=True, help_text='For bank transfers/terminal', max_length=255, verbose_name='Transaction ID')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Receipt Image')),
                ('date_paid', models.DateTimeField(auto_now_add=True, verbose_name='Date Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='contract.contract')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField(verbose_name='Month Number')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('plan_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Planned Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paid Amount')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Debt')),
                ('is_late', models.BooleanField(default=False, verbose_name='Is Late')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='contract.contract')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['contract', 'month_number'],
            },
        ),
    ]
