# Generated by Django 5.2.10 on 2026-08-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminateContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField(verbose_name='Termination Date')),
                ('termination_reason', models.TextField(blank=True, verbose_name='Termination Reason')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fine Amount')),
                ('fine_paid', models.BooleanField(default=False, verbose_name='Fine Paid')),
                ('planned_refund', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Planned Refund Amount')),
                ('paid_refund', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Paid Refund Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='contract.contract')),
            ],
            options={
                'verbose_name': 'Terminated Contract',
                'verbose_name_plural': 'Terminated Contracts',
            },
        ),
        migrations.CreateModel(
            name='TerminateContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Payment Amount')),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK', 'Bank Transfer'), ('MATERIAL', 'Material')], default='CASH', max_length=20, verbose_name='Payment Type')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Transaction ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('termination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_payments', to='contract.terminatecontract')),
            ],
            options={
                'verbose_name': 'Termination Payment',
                'verbose_name_plural': 'Termination Payments',
            },
        ),
    ]
