# Generated by Django 5.2.10 on 2026-08-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_terminatecontract_terminatecontractpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='last_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Last Payment'),
        ),
    ]
