# Generated by Django 5.2.10 on 2026-08-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_last_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='discount_amount',
        ),
    ]
