# Generated by Django 5.2.10 on 2026-08-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_remove_contract_discount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentlog',
            options={'ordering': ['date_paid'], 'verbose_name': 'Payment Log', 'verbose_name_plural': 'Payment Logs'},
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='payment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='contract.paymentrecord'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='excess_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Excess / Overpayment'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='is_debt_saved_to_next_month',
            field=models.BooleanField(default=False, verbose_name='Debt Carried Over'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debt'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='plan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Planned Amount'),
        ),
    ]
