# Generated by Django 5.2.10 on 2026-08-30 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_paymentlog_options_paymentlog_payment_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='date_paid',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Paid'),
        ),
    ]
