# Generated by Django 5.2.10 on 2026-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_paymentlog_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='down_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Down Payment Date'),
        ),
    ]
