# Generated by Django 5.2.10 on 2026-09-24 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_contracttemplate_content_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='staff_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff_member': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='staff_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff_member': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
