# Generated by Django 5.2.10 on 2026-09-29 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_contract_staff_member_paymentlog_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_made',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Contract Made'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(verbose_name='Installment Start Date'),
        ),
    ]
