# Generated by Django 5.2.10 on 2026-09-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_date_made_alter_contract_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contract ID'),
        ),
    ]
