# Generated by Django 5.2.10 on 2026-09-30 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_populate_contract_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.IntegerField(default=1, verbose_name='Contract ID'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('company', 'contract_id')},
        ),
    ]
