# Generated by Django 5.2.10 on 2026-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_alter_contract_contract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.IntegerField(verbose_name='Contract ID'),
        ),
    ]
