# Generated by Django 5.2.10 on 2026-10-02 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_alter_contract_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='date_paid',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Date Paid'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='Due Date'),
        ),
    ]
