# Generated by Django 5.2.10 on 2026-01-17 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_start_time', models.TimeField(default='08:30', help_text='Start time for the schedule timeline (e.g., 08:30)', verbose_name='Schedule Start Time')),
                ('schedule_end_time', models.TimeField(default='20:00', help_text='End time for the schedule timeline (e.g., 20:00)', verbose_name='Schedule End Time')),
                ('time_slot_minutes', models.PositiveIntegerField(default=30, help_text='Duration of each time slot in minutes (15-120)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Time Slot Duration (minutes)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
    ]
