# Generated by Django 5.2.10 on 2026-01-17 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsettings',
            name='schedule_end_time',
            field=models.TimeField(default=datetime.time(20, 0), help_text='End time for the schedule timeline (e.g., 20:00)', verbose_name='Schedule End Time'),
        ),
        migrations.AlterField(
            model_name='dashboardsettings',
            name='schedule_start_time',
            field=models.TimeField(default=datetime.time(8, 30), help_text='Start time for the schedule timeline (e.g., 08:30)', verbose_name='Schedule Start Time'),
        ),
    ]
