# Generated by Django 5.2.10 on 2026-08-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Building Name / Number')),
                ('block_number', models.CharField(blank=True, max_length=255, verbose_name='Block Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('floor_count', models.PositiveIntegerField(default=1, verbose_name='Floor Count')),
                ('entrance_count', models.PositiveIntegerField(default=1, verbose_name='Entrance Count')),
                ('apartment_count', models.PositiveIntegerField(default=1, verbose_name='Apartment Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=50, verbose_name='Apartment Number')),
                ('floor_number', models.PositiveIntegerField(verbose_name='Floor Number')),
                ('entrance_number', models.PositiveIntegerField(verbose_name='Entrance Number')),
                ('living_room_count', models.PositiveIntegerField(default=1, verbose_name='Living Room Count')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Area (m2)')),
                ('living_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Living Area (m2)')),
                ('balcony_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balcony Area (m2)')),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='apartment_plans/', verbose_name='Floor Plan Image')),
                ('is_real', models.BooleanField(default=True, help_text='Set to False if cloned/archived for a terminated contract.', verbose_name='Is Real (Active)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='building.building')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'ordering': ['entrance_number', 'floor_number', 'apartment_number'],
            },
        ),
    ]
