# Generated by Django 5.2.10 on 2026-08-09 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff_member': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buildings', to=settings.AUTH_USER_MODEL),
        ),
    ]
