# Generated by Django 5.2.10 on 2026-09-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_building_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='apartments_per_floor',
            field=models.PositiveIntegerField(default=4, verbose_name='Apartments per Floor'),
        ),
    ]
