# Generated by Django 5.2.10 on 2026-09-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_building_apartments_per_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='cadastre_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cadastre Number'),
        ),
        migrations.AddField(
            model_name='building',
            name='construction_footprint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Construction Footprint (sqm)'),
        ),
        migrations.AddField(
            model_name='building',
            name='delivery_quarter',
            field=models.CharField(blank=True, help_text='e.g. 2029 йилнинг 4-чораги', max_length=100, verbose_name='Delivery Date/Quarter'),
        ),
        migrations.AddField(
            model_name='building',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Land Area (sqm)'),
        ),
    ]
